analyzer:
  errors:
    invalid_annotation_target: ignore
    duplicate_ignore: ignore
    deprecated_member_use: ignore

formatter:
  trailing_commas: preserve
  page_width: 80


include: package:flutter_lints/flutter.yaml

linter:

  rules:

